### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by MartkCz** [Joseki/FileTemplate#1]
Syntax like latte: **{$CONTROL$|lower}**, **{$CONTROL$|replace:'foo','bar'}**. Usage in config and templates.

**Comment by castamir** [comment]
I'm wondering...  Latte template with helpers inside
or 
PhpStorm in-place `${VARIABLE}`s for compatibility with PhpStorm template syntax and perhaps some filters in config?

**Comment by MartkCz** [comment]
It's good idea. `${VARIABLE}` is better, nicer and shorter than `{$VARIABLE$}`.

**Comment by castamir** [comment]
- syntax changed to `${VARIABLE}` in both config and templates
- changed command name to `joseki:file-template`

Still not sure about filters... @AntikCz could you give me any real use-case for those filters?

**Comment by MartkCz** [comment]
I very often need first character lowercase or uppercase. Functions with parameters probably not.

``` php
class ${CLASS|firstUpper} {

    /**
     * @var \Forms\${CLASS|firstUpper} @inject
     */
    public $${CLASS}Form;
}
```

**Comment by castamir** [comment]
I need to think about a possible implementation... if I allow filters (like in latte), then I will need to allow you to define your own custom filters, because fixed filters suxs. 

I'll try to look at it during a weekend (I've been quite bussy lately, sorry about that).

**Comment by castamir** [comment]
I'm not going to implement this, sorry.
